CREATE DATABASE Crowdfunding_db;
USE Crowdfunding_db;
CREATE TABLE CATEGORY (
  CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);
CREATE TABLE FUNDRAISER (
  FUNDRAISER_ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGANIZER VARCHAR(255) NOT NULL,
  CAPTION VARCHAR(255),
  TARGET_FUNDING DECIMAL(10,2) NOT NULL,
  CURRENT_FUNDING DECIMAL(10,2) DEFAULT 0.00,
  CITY VARCHAR(100),
  ACTIVE BOOLEAN DEFAULT TRUE,
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
INSERT INTO CATEGORY (NAME) VALUES 
('Medical'),
('Education'),
('Crisis Relief');
INSERT INTO FUNDRAISER (ORGANIZER, CAPTION, TARGET_FUNDING, CURRENT_FUNDING, CITY, ACTIVE, CATEGORY_ID) 
VALUES 
('Jacky Chan', 'Help Jacky Family After Flood', 25000, 3415, 'Goldcoast', TRUE, 3),
('Lal bhahadur Gurung', 'Support Lal’s Cancer Treatment', 12600, 8255, 'Kathmandu', TRUE, 1),
('St. Lawrence School', 'Help Build a Library', 19500, 22000, 'Chigaco', FALSE, 2),
('Mohan Magar', 'Earthquake Relief Fund', 19400, 1253, 'Pokhara', TRUE, 3),
('Eco Club', 'Plant 10000 Trees', 24000, 6530, 'Munich', TRUE, 2);
